import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import LenisProvider from '@/libs/react-lenis'
import ParticlesBackground from '@/components/ParticlesBackground/page'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <LenisProvider root>
      <html lang="en">
        <body className={inter.className}>
            <ParticlesBackground/>
          <div className="flex justify-center">
            <Providers>{children}</Providers>
          </div>
        </body>
      </html>
    </LenisProvider>
  )
}
